# Generated by Django 5.0.4 on 2024-05-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
    ]
