# Generated by Django 5.0.4 on 2024-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_productsize_delete_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(default=list, verbose_name='Доступні розміри'),
        ),
    ]
