# Generated by Django 5.0.4 on 2024-05-04 14:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета опис')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Ключові слова')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('index', models.IntegerField(blank=True, default=-1, help_text='Вкажіть порядковий номер для сортування', verbose_name='Індекс')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'ordering': ['index'],
            },
        ),
    ]
